name: quran_listienning
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.1.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  animated_splash_screen: ^1.0.1+2
  http: ^0.12.2
  flutter_bloc: ^6.1.0
  equatable: ^1.2.5
  intl: ^0.16.1
  assets_audio_player: ^2.0.13+1
  page_transition: ^1.1.7+2
  move_to_background: ^1.0.1
  flutter_staggered_animations: ^0.1.2
  url_launcher: ^5.7.10
  font_awesome_flutter: ^8.10.1
  cached_network_image: ^2.5.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.24
  like_button: ^1.0.4

dev_dependencies:
  hive_generator: ^0.8.2
  build_runner: ^1.10.11
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
